version: '2'
services:

  power-pijuice:
    image: shocki/rpi-pijuice-mqtt
    privileged: true

  usb-power:
    image: shocki/rpi-mqtt-usb-power-switch
    privileged: true

  radar-reader:
    image: shocki/rpi-radar-reader:0.0.3
    privileged: true
    restart: always
    ports:
      - 5555:5555
    labels:
      io.balena.features.kernel-modules: '1'
    volumes:
      - radar-data:/radar

  camera-server:
    image: shocki/rpi-cam-server
    privileged: true
    restart: always
    network_mode: "host"
    environment:
      - STUN_SERVER=stun:stun.l.google.com:19302
      - TURN_SERVER=turn:192.168.0.21:3478
      - TURN_USERNAME=radar-pi
      - TURN_PASSWORD=KYfFvFke2E7iFs
    labels:
      io.balena.features.kernel-modules: '1'

volumes:
  radar-data: