version: '2'
services:

  data-loader:
    image: httpd:2.4.46-alpine
    ports:
      - "80:80"
    volumes:
        - radar-data:/usr/local/apache2/htdocs/

  mqtt-broker:
    build: mqtt-broker
    ports:
      - "1883:1883"
    volumes:
      - mosquitto-data:/mosquitto/data
    restart: unless-stopped

  config-manager:
    image: shocki/radr-config-manager
    environment:
      - MQTT_BROKER_ADDRESS=http://mqtt-broker:1883
      - RADR_CONFIG_DIRECTORY=/config
      - RADR_VAR_DIRECTORY=/var
      - RADR_AUTOMATIC_CONFIG_UPDATES=true
    volumes:
      - config:/config
      - config-manager:/var
    restart: unless-stopped

  storage-service:
    image: shocki/rpi-storageapi
    volumes:
      - radar-data:/data
      - config:/config
    ports:
      - "2020:80"

  power-pijuice:
    image: shocki/rpi-pijuice-mqtt
    privileged: true
    volumes:
      - radar-data:/data
    environment:
      - MQTT_BROKER_ADDRESS=http://mqtt-broker:1883

  usb-power:
    image: shocki/rpi-mqtt-usb-power-switch:0.2.2
    privileged: true
    environment:
      - MQTT_BROKER_ADDRESS=http://mqtt-broker:1883

#  rdm-processor:
#    image: shocki/rpi-rdm-processor
#    ports:
#      - 5556:5556
#    volumes:
#      - radar-data:/data
#    environment:
#      - ZMQ_INPUT=radar-reader:5555
#      - STORAGE_API_URL=http://storage-service
#      - MQTT_BROKER_ADDRESS=tcp://mqtt-broker:1883

  radar-reader:
    image: shocki/rpi-radar-reader:1-2-6
    privileged: true
    restart: always
    ports:
      - "5555:5555"
    labels:
      io.balena.features.kernel-modules: '1'
    volumes:
      - radar-data:/radar
    environment:
      - MQTT_BROKER=tcp://mqtt-broker:1883

#  mic-reader:
#    image: shocki/rpi-mic-stream
#    privileged: true
#    ports:
#      - 5554:5554
#    labels:
#      io.balena.features.kernel-modules: '1'
#    command: -ac 1 -ar 8000 -f alsa -i hw:1,0 -acodec mp3 -b:a 128k -f rtp rtp://0.0.0.0:5554

  cam-reader:
    image: shocki/rpi-cam-reader
    privileged: true
    volumes:
      - radar-data:/data
    ports:
      - "5553:5553"
    labels:
      io.balena.features.kernel-modules: '1'
    environment:
      - STORAGE_API_URL=http://storage-service
      - MQTT_BROKER_ADDRESS=tcp://mqtt-broker:1883

volumes:
  radar-data:
  mosquitto-data:
  config-manager:
  config:
